name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: echo "::set-output name=version::${GITHUB_REF:10}"
        id: release
      - name: "Gradle Build"
        run: ./gradlew build -Pversion=${{ steps.release.outputs.version }}
      - name: "Publish packages to GitHub"
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish -Pversion=${{ steps.release.outputs.version }}
      - name: "Publish Zip to GitHub"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./swagger-coverage-commandline/build/distributions/swagger-coverage-commandline-${{ steps.release.outputs.version }}.zip
          asset_name: swagger-coverage-${{ steps.release.outputs.version }}.zip
          asset_content_type: application/octet-stream
      - name: "Publish Tar to GitHub"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./swagger-coverage-commandline/build/distributions/swagger-coverage-commandline-${{ steps.release.outputs.version }}.tar
          asset_name: swagger-coverage-${{ steps.release.outputs.version }}.tar
          asset_content_type: application/octet-stream